# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_free',
        ),
    ]
